version: '3.8'

services:
  api:
    build: .
    container_name: drivetrack_api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./drivetrack.db:/app/drivetrack.db
    depends_on:
      - minio
    ports:
      - "8010:8010" # Exponemos la API en el puerto 8010 para evitar conflictos con django (8000)
    networks:
      - drivetrack_net
      - npm_network

  minio:
    image: minio/minio:latest
    container_name: drivetrack_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000" # API Minio
      - "9001:9001" # Consola UI Minio
    networks:
      - drivetrack_net
      - npm_network

networks:
  drivetrack_net:
    driver: bridge # Red personalizada que aísla los contenedores pero permite que se hablen internamente
  npm_network:
    name: nginx-proxy-manager_default
    external: true

volumes:
  minio_data:
